<?php

namespace App\Entity;

use App\Repository\RagQueryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * One logged AI-assistant query, used for per-user usage metering so the
 * (real) generation cost stays bounded per access tier. Stores the question
 * text, whether it was served from cache or freshly generated by the model,
 * and how many AI credits it cost.
 */
#[ORM\Entity(repositoryClass: RagQueryRepository::class)]
#[ORM\Table(name: 'rag_query')]
#[ORM\Index(name: 'idx_rag_query_user_time', columns: ['user_id', 'created_at'])]
class RagQuery
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[ORM\Column(type: 'bigint')]
    private ?int $id = null;

    #[ORM\Column(name: 'user_id')]
    private int $userId;

    #[ORM\Column(name: 'volume_id', nullable: true)]
    private ?int $volumeId = null;

    #[ORM\Column(name: 'question', type: 'text', nullable: true)]
    private ?string $question = null;

    /** True = odpowiedź z cache (bez wywołania modelu), false = wygenerowana przez AI. */
    #[ORM\Column(name: 'cached', options: ['default' => false])]
    private bool $cached = false;

    /** Koszt zapytania w kredytach AI (0 dla użytkowników bez limitu). */
    #[ORM\Column(name: 'credits_cost', type: 'smallint', options: ['default' => 0])]
    private int $creditsCost = 0;

    /** Model użyty do wygenerowania odpowiedzi (np. google/gemini-2.5-flash) lub null dla cache. */
    #[ORM\Column(name: 'model', length: 64, nullable: true)]
    private ?string $model = null;

    #[ORM\Column(name: 'input_tokens', options: ['default' => 0])]
    private int $inputTokens = 0;

    #[ORM\Column(name: 'output_tokens', options: ['default' => 0])]
    private int $outputTokens = 0;

    /** Realny koszt zapytania w USD (z OpenRouter usage accounting; 0 dla cache/Ollama). */
    #[ORM\Column(name: 'cost_usd', type: 'decimal', precision: 12, scale: 6, options: ['default' => 0])]
    private string $costUsd = '0';

    #[ORM\Column(name: 'created_at', type: 'datetime_immutable')]
    private \DateTimeInterface $createdAt;

    /** Wskaźnik na trwałą treść odpowiedzi (historia per konto). NULL = usunięta z historii. */
    #[ORM\ManyToOne(targetEntity: RagAnswer::class)]
    #[ORM\JoinColumn(name: 'answer_id', referencedColumnName: 'id', nullable: true, onDelete: 'SET NULL')]
    private ?RagAnswer $answer = null;

    /** Przypięcie „wartościowej” odpowiedzi przez użytkownika. */
    #[ORM\Column(options: ['default' => false])]
    private bool $pinned = false;

    #[ORM\Column(name: 'pinned_at', type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeInterface $pinnedAt = null;

    public function __construct(
        int $userId,
        ?int $volumeId = null,
        ?string $question = null,
        bool $cached = false,
        int $creditsCost = 0,
    ) {
        $this->userId = $userId;
        $this->volumeId = $volumeId;
        $this->question = $question;
        $this->cached = $cached;
        $this->creditsCost = $creditsCost;
        $this->createdAt = new \DateTimeImmutable();
    }

    /** Zapisuje realne zużycie z modelu (tokeny + koszt USD). */
    public function setUsage(?string $model, int $inputTokens, int $outputTokens, float $costUsd): static
    {
        $this->model = $model;
        $this->inputTokens = max(0, $inputTokens);
        $this->outputTokens = max(0, $outputTokens);
        $this->costUsd = number_format(max(0, $costUsd), 6, '.', '');
        return $this;
    }

    public function getId(): ?int { return $this->id; }
    public function getUserId(): int { return $this->userId; }
    public function getVolumeId(): ?int { return $this->volumeId; }
    public function getQuestion(): ?string { return $this->question; }
    public function isCached(): bool { return $this->cached; }
    public function getCreditsCost(): int { return $this->creditsCost; }
    public function getModel(): ?string { return $this->model; }
    public function getInputTokens(): int { return $this->inputTokens; }
    public function getOutputTokens(): int { return $this->outputTokens; }
    public function getCostUsd(): float { return (float) $this->costUsd; }
    public function getCreatedAt(): \DateTimeInterface { return $this->createdAt; }

    public function getAnswer(): ?RagAnswer { return $this->answer; }
    public function setAnswer(?RagAnswer $answer): static { $this->answer = $answer; return $this; }
    public function isPinned(): bool { return $this->pinned; }
    public function setPinned(bool $pinned): static
    {
        $this->pinned = $pinned;
        $this->pinnedAt = $pinned ? new \DateTimeImmutable() : null;
        return $this;
    }
    public function getPinnedAt(): ?\DateTimeInterface { return $this->pinnedAt; }
}
